In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')

In [4]:
len(df)
# len is the value of tables read

3

In [5]:
# since there are 3 tables read, examine each to determine the table we wanted
df[0].head()
# examining the first data frame

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [6]:
# It is confirmed df[0] is the table we seek

In [7]:
pdf=df[0] # reassign to work with variable pdf

pdf.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [8]:
print(pdf.shape)

(288, 3)

In [9]:
# code to extract info from pdf.iloc

new_df=[]; nblist=''
for i in range(pdf.shape[0]):
    
    item=pdf.iloc[i]
    pcode=item[0]; borough=item[1]; nbhood=item[2]; 

    if borough =='Not assigned' and nbhood == 'Not assigned':
        pcode=''
    
    if pcode != '':
        
        if borough != 'Not assigned' and nbhood =='Not assigned':
            nbhood=borough
            
        if i > 0 :
            if pcode == pdf.iloc[i-1,0]:
                nblist += ', ' + nbhood
            else:
                nblist=nbhood
        else:  
             nblist=nbhood 
                
        if i < pdf.shape[0]:
            if pcode != pdf.iloc[i+1,0]:
                item[2] = nblist
                new_df.append(item)
                nblist=''
        else:
            if nblist !='':
                item[2] = nblist
                new_df.append(item)
                nblist=''

In [10]:
new_pdf=pd.DataFrame(new_df)
new_pdf.head(10)

   Postcode           Borough                     Neighbourhood
2       M3A        North York                         Parkwoods
3       M4A        North York                  Victoria Village
5       M5A  Downtown Toronto         Harbourfront, Regent Park
7       M6A        North York  Lawrence Heights, Lawrence Manor
8       M7A      Queen's Park                      Queen's Park
10      M9A         Etobicoke                  Islington Avenue
12      M1B       Scarborough                    Rouge, Malvern
14      M3B        North York                   Don Mills North
16      M4B         East York   Woodbine Gardens, Parkview Hill
18      M5B  Downtown Toronto          Ryerson, Garden District

### answer to last part of the assignment part 1

In [11]:
new_pdf.shape # requested by assigment part 1

(103, 3)